SELECT DATE_FORMAT(O.SALES_DATE,"%Y-%m-%d") SALES_DATE, O.PRODUCT_ID, O.USER_ID, O.SALES_AMOUNT
FROM ONLINE_SALE O
WHERE DATE_FORMAT(O.SALES_DATE, "%Y-%m") = "2022-03"
UNION ALL
SELECT DATE_FORMAT(OFF.SALES_DATE,"%Y-%m-%d") SALES_DATE, OFF.PRODUCT_ID, NULL, OFF.SALES_AMOUNT
FROM OFFLINE_SALE OFF
WHERE DATE_FORMAT(OFF.SALES_DATE, "%Y-%m") = "2022-03"

ORDER BY SALES_DATE, PRODUCT_ID, USER_ID
